# Generated by Django 2.0.1 on 2018-01-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20180115_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-board_id', '-pk')},
        ),
    ]
