# Generated by Django 2.0.1 on 2018-02-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20180116_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-board_id', '-pk')},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='email',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
