# Generated by Django 2.0.1 on 2018-04-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180322_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='http://13.125.76.112/statics/profile/1.png', max_length=200),
        ),
    ]
