# Generated by Django 2.0.1 on 2018-08-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declare', '0004_auto_20180805_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declare',
            old_name='board_id',
            new_name='board',
        ),
    ]
