# Generated by Django 2.0.1 on 2018-08-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declare', '0005_auto_20180805_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='declare',
            old_name='board',
            new_name='board_id',
        ),
    ]
