# Generated by Django 2.0.1 on 2018-02-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('board_id', '-created')},
        ),
    ]
