# Generated by Django 2.0.1 on 2018-02-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180219_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='email',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='board',
            name='title',
        ),
    ]
