# Generated by Django 2.0.1 on 2018-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180219_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='background_color',
            new_name='background_url',
        ),
    ]
