# Generated by Django 2.0.1 on 2018-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180220_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
