# Generated by Django 2.0.1 on 2018-03-27 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_category_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.AlterField(
            model_name='board',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_board', to='board.Category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_board', to='user.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='user.User'),
        ),
    ]
