# Generated by Django 2.0.1 on 2018-03-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20180327_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='user',
        ),
    ]
