# Generated by Django 2.0.1 on 2018-04-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20180328_0323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('board_id', 'user')},
        ),
    ]
