# Generated by Django 2.0.1 on 2018-04-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20180415_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
