# Generated by Django 2.0.1 on 2018-06-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20180415_0931'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('board_id', 'user')},
        ),
    ]
