# Generated by Django 2.0.1 on 2018-02-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagel_url', models.CharField(max_length=200)),
                ('font_color', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
