# Generated by Django 2.0.1 on 2018-02-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardimage',
            old_name='imagel_url',
            new_name='image_url',
        ),
    ]
